version: 0.2

#env:
#  parameter-store:
#    ssh_key: "/lucas_ssh_key"

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10
      # name: version
    commands:
    #  - yum install -y gcc-c++ make
    #  - curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
    #  - sudo yum install -y nodejs
      - npm install -g serverless
      - npm install serverless-import-apigateway --save-dev
      #- echo "$ssh_key" > ~/.ssh/id_rsa
      #- chmod 600 ~/.ssh/id_rsa
      #- eval `ssh-agent`
      #- ssh-add  ~/.ssh/id_rsa
      - git clone git@github.com:lucasteracloud/test-serverless.git
  
  pre_build:
    commands:
      - echo "Nothing in pre_build"
  
  build:
    commands:
      - cd test-serverless
      - sls deploy --stage api
